version: "3.1"

services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - "/app/node_modules"
      - "./:/app"
